# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-19 13:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alerts',
            fields=[
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('alert_num', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='AltDiseases',
            fields=[
                ('alt_name', models.CharField(max_length=250, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Diseases',
            fields=[
                ('name', models.CharField(max_length=250, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Districts',
            fields=[
                ('name', models.CharField(max_length=250, primary_key=True, serialize=False)),
                ('lng', models.FloatField()),
                ('lat', models.FloatField()),
                ('zoom', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='LHCP',
            fields=[
                ('name', models.CharField(max_length=250)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('code', models.AutoField(primary_key=True, serialize=False)),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='map.Alerts')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='map.Districts')),
            ],
        ),
        migrations.CreateModel(
            name='Phones',
            fields=[
                ('number', models.CharField(max_length=250, primary_key=True, serialize=False)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='map.LHCP')),
            ],
        ),
        migrations.CreateModel(
            name='Reports',
            fields=[
                ('date', models.DateField()),
                ('disease', models.CharField(max_length=250)),
                ('case_count', models.IntegerField(null=True)),
                ('death_count', models.IntegerField(null=True)),
                ('report_num', models.AutoField(primary_key=True, serialize=False)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='map.Districts')),
                ('phone_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='map.Phones')),
            ],
        ),
        migrations.AddField(
            model_name='altdiseases',
            name='official_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='map.Diseases'),
        ),
        migrations.AddField(
            model_name='alerts',
            name='disease',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='map.Diseases'),
        ),
        migrations.AddField(
            model_name='alerts',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='map.Districts'),
        ),
    ]
