# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-20 13:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_remove_lhcp_alert'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reports',
            name='district',
        ),
    ]
