# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-24 20:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0003_remove_reports_district'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alerts',
            name='disease',
        ),
        migrations.RemoveField(
            model_name='alerts',
            name='district',
        ),
        migrations.AlterField(
            model_name='reports',
            name='disease',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='map.Diseases'),
        ),
        migrations.DeleteModel(
            name='Alerts',
        ),
    ]
