# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-24 21:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0004_auto_20170724_1645'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeathReports',
            fields=[
                ('reports_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='map.Reports')),
                ('count', models.IntegerField()),
            ],
            bases=('map.reports',),
        ),
        migrations.CreateModel(
            name='HeadReports',
            fields=[
                ('reports_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='map.Reports')),
                ('count', models.IntegerField()),
            ],
            bases=('map.reports',),
        ),
        migrations.RemoveField(
            model_name='reports',
            name='case_count',
        ),
        migrations.RemoveField(
            model_name='reports',
            name='death_count',
        ),
    ]
