# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-03 15:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('name', models.CharField(max_length=250)),
                ('code', models.IntegerField()),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('state_code', models.CharField(max_length=250)),
                ('name_state', models.CharField(max_length=250, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Phones',
            fields=[
                ('number', models.CharField(max_length=250, primary_key=True, serialize=False)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demo.Cities')),
            ],
        ),
        migrations.CreateModel(
            name='Reports',
            fields=[
                ('date', models.DateField()),
                ('disease', models.CharField(max_length=250)),
                ('report_num', models.AutoField(primary_key=True, serialize=False)),
                ('count', models.IntegerField()),
                ('phone_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demo.Phones')),
            ],
        ),
    ]
