# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-03 16:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phones',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='phones',
            name='lng',
        ),
    ]
