# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-15 15:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0003_auto_20170810_1848'),
        ('demo', '0003_auto_20170811_2354'),
    ]

    operations = [
    ]
