# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-18 18:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AltDiseases',
            fields=[
                ('alt_name', models.CharField(max_length=250, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Diseases',
            fields=[
                ('name', models.CharField(max_length=250, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Districts',
            fields=[
                ('name', models.CharField(max_length=250, primary_key=True, serialize=False)),
                ('lng', models.FloatField()),
                ('lat', models.FloatField()),
                ('zoom', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='LHCP',
            fields=[
                ('name', models.CharField(max_length=250)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('code', models.AutoField(primary_key=True, serialize=False)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simulation.Districts')),
            ],
        ),
        migrations.CreateModel(
            name='Phones',
            fields=[
                ('number', models.CharField(max_length=250, primary_key=True, serialize=False)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simulation.LHCP')),
            ],
        ),
        migrations.CreateModel(
            name='Reports',
            fields=[
                ('date', models.DateField()),
                ('report_num', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='DeathReports',
            fields=[
                ('reports_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='simulation.Reports')),
                ('count', models.IntegerField()),
            ],
            bases=('simulation.reports',),
        ),
        migrations.CreateModel(
            name='HeadReports',
            fields=[
                ('reports_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='simulation.Reports')),
                ('count', models.IntegerField()),
            ],
            bases=('simulation.reports',),
        ),
        migrations.AddField(
            model_name='reports',
            name='disease',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simulation.Diseases'),
        ),
        migrations.AddField(
            model_name='reports',
            name='phone_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simulation.Phones'),
        ),
        migrations.AddField(
            model_name='altdiseases',
            name='official_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simulation.Diseases'),
        ),
    ]
